# -*- coding: utf-8 -*-
"""Case ADUI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UNcZFA579eNnZ67s_vydK5bGXSGrdyax
"""

# prompt: O arquivo Alunos.csv possui as seguintes colunas: aluno_id, nome, turma, escola_id
# O arquivo Testes.csv possui as seguntes colunas: aluno_id, disciplina, nota, bimestre
# Crie um código que una as duas tabelas através dos campos aluno_id e armazene na tabela AlunosxTestes com os seguintes campos: aluno_id, nome, turma, disciplina, nota, bimestre.
# Ordene a tabela AlunosxTestes pelos campos turma em ordem crescente e nome em ordem crescente.
# Salve a tabela AlunosxTestes no arquivo alunos_avaliacoes.csv

import pandas as pd

# Load the datasets
alunos_df = pd.read_csv('Alunos.csv', encoding='latin1')
testes_df = pd.read_csv('Testes.csv', encoding='latin1')

# Merge the two dataframes
alunos_avaliacoes_df = pd.merge(alunos_df, testes_df, on='aluno_id')

# Select and reorder the columns
alunos_avaliacoes_df = alunos_avaliacoes_df[['aluno_id', 'nome', 'turma', 'disciplina', 'nota', 'bimestre']]

# Sort the merged dataframe
alunos_avaliacoes_df = alunos_avaliacoes_df.sort_values(by=['turma', 'nome'], ascending=[True, True])

# Save the result to a new CSV file
alunos_avaliacoes_df.to_csv('alunos_avaliacoes.csv', index=False)